// Code generated by "stringer -type=TokenKind,NodeKind,DiagnosticKind -output=kind_string.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[EOF-1]
	_ = x[BOM-2]
	_ = x[Whitespace-3]
	_ = x[Newline-4]
	_ = x[LineComment-5]
	_ = x[BlockComment-6]
	_ = x[Identifier-7]
	_ = x[Number-8]
	_ = x[OpenBrace-9]
	_ = x[CloseBrace-10]
	_ = x[OpenBracket-11]
	_ = x[CloseBracket-12]
	_ = x[OpenParen-13]
	_ = x[CloseParen-14]
	_ = x[Plus-15]
	_ = x[Minus-16]
	_ = x[Star-17]
	_ = x[Slash-18]
	_ = x[Percent-19]
	_ = x[And-20]
	_ = x[Or-21]
	_ = x[Bang-22]
	_ = x[Equal-23]
	_ = x[EqualEqual-24]
	_ = x[NotEqual-25]
	_ = x[Less-26]
	_ = x[LessEqual-27]
	_ = x[Greater-28]
	_ = x[GreaterEqual-29]
	_ = x[Arrow-30]
	_ = x[Colon-31]
	_ = x[DoubleColon-32]
	_ = x[Question-33]
	_ = x[Dot-34]
	_ = x[Ellipsis-35]
	_ = x[Comma-36]
	_ = x[QuoteOpen-37]
	_ = x[QuoteClose-38]
	_ = x[TemplateText-39]
	_ = x[InterpolationOpen-40]
	_ = x[DirectiveOpen-41]
	_ = x[StripMarker-42]
	_ = x[TemplateSequenceEnd-43]
	_ = x[HeredocOpen-44]
	_ = x[HeredocMarker-45]
	_ = x[HeredocEndMarker-46]
	_ = x[tokenKindCount-47]
}

const _TokenKind_name = "InvalidEOFBOMWhitespaceNewlineLineCommentBlockCommentIdentifierNumberOpenBraceCloseBraceOpenBracketCloseBracketOpenParenCloseParenPlusMinusStarSlashPercentAndOrBangEqualEqualEqualNotEqualLessLessEqualGreaterGreaterEqualArrowColonDoubleColonQuestionDotEllipsisCommaQuoteOpenQuoteCloseTemplateTextInterpolationOpenDirectiveOpenStripMarkerTemplateSequenceEndHeredocOpenHeredocMarkerHeredocEndMarkertokenKindCount"

var _TokenKind_index = [...]uint16{0, 7, 10, 13, 23, 30, 41, 53, 63, 69, 78, 88, 99, 111, 120, 130, 134, 139, 143, 148, 155, 158, 160, 164, 169, 179, 187, 191, 200, 207, 219, 224, 229, 240, 248, 251, 259, 264, 273, 283, 295, 312, 325, 336, 355, 366, 379, 395, 409}

func (i TokenKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidNode-0]
	_ = x[File-1]
	_ = x[ErrorNode-2]
	_ = x[LiteralExpression-3]
	_ = x[VariableExpression-4]
	_ = x[ParenthesizedExpression-5]
	_ = x[UnaryExpression-6]
	_ = x[BinaryExpression-7]
	_ = x[ConditionalExpression-8]
	_ = x[FunctionCallExpression-9]
	_ = x[TraversalExpression-10]
	_ = x[AttributeAccess-11]
	_ = x[IndexAccess-12]
	_ = x[LegacyIndexAccess-13]
	_ = x[AttributeSplat-14]
	_ = x[FullSplat-15]
	_ = x[TupleExpression-16]
	_ = x[ObjectExpression-17]
	_ = x[ObjectItem-18]
	_ = x[ForExpression-19]
	_ = x[TemplateExpression-20]
	_ = x[TemplateInterpolation-21]
	_ = x[TemplateDirective-22]
	_ = x[TemplateIf-23]
	_ = x[TemplateFor-24]
	_ = x[Body-25]
	_ = x[Attribute-26]
	_ = x[Block-27]
	_ = x[BlockLabel-28]
	_ = x[nodeKindCount-29]
}

const _NodeKind_name = "InvalidNodeFileErrorNodeLiteralExpressionVariableExpressionParenthesizedExpressionUnaryExpressionBinaryExpressionConditionalExpressionFunctionCallExpressionTraversalExpressionAttributeAccessIndexAccessLegacyIndexAccessAttributeSplatFullSplatTupleExpressionObjectExpressionObjectItemForExpressionTemplateExpressionTemplateInterpolationTemplateDirectiveTemplateIfTemplateForBodyAttributeBlockBlockLabelnodeKindCount"

var _NodeKind_index = [...]uint16{0, 11, 15, 24, 41, 59, 82, 97, 113, 134, 156, 175, 190, 201, 218, 232, 241, 256, 272, 282, 295, 313, 334, 351, 361, 372, 376, 385, 390, 400, 413}

func (i NodeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeKind_index)-1 {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[idx]:_NodeKind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidUTF8-0]
	_ = x[InvalidCharacter-1]
	_ = x[UnterminatedBlockComment-2]
	_ = x[UnterminatedQuotedTemplate-3]
	_ = x[UnterminatedTemplateSequence-4]
	_ = x[InvalidEscape-5]
	_ = x[NewlineInQuotedTemplate-6]
	_ = x[UnterminatedHeredoc-7]
	_ = x[ExpectedExpression-8]
	_ = x[UnexpectedToken-9]
	_ = x[ExpectedClosingParen-10]
	_ = x[ExpectedClosingBracket-11]
	_ = x[ExpectedConditionalColon-12]
	_ = x[ExpectedArgumentSeparator-13]
	_ = x[ExpectedAttributeName-14]
	_ = x[ExpectedFunctionName-15]
	_ = x[ExpectedOpeningParen-16]
	_ = x[InvalidLegacyIndex-17]
	_ = x[NestedAttributeSplat-18]
	_ = x[NestingLimitExceeded-19]
	_ = x[InvalidNumber-20]
	_ = x[ExpectedTupleSeparator-21]
	_ = x[ExpectedClosingBrace-22]
	_ = x[ExpectedObjectValueSeparator-23]
	_ = x[ExpectedObjectItemSeparator-24]
	_ = x[ExpectedForVariable-25]
	_ = x[ExpectedForIn-26]
	_ = x[ExpectedForColon-27]
	_ = x[ExpectedForArrow-28]
	_ = x[UnexpectedForKey-29]
	_ = x[UnexpectedForGrouping-30]
	_ = x[ExpectedTemplateSequenceEnd-31]
	_ = x[ExpectedTemplateDirective-32]
	_ = x[UnknownTemplateDirective-33]
	_ = x[UnexpectedTemplateDirective-34]
	_ = x[ExpectedTemplateEndIf-35]
	_ = x[ExpectedTemplateEndFor-36]
	_ = x[ExpectedBodyItem-37]
	_ = x[ExpectedAttributeOrBlock-38]
	_ = x[ExpectedBodyItemSeparator-39]
	_ = x[ExpectedBlockOpeningBrace-40]
	_ = x[ExpectedLiteralBlockLabel-41]
	_ = x[ExpectedSingleLineAttribute-42]
	_ = x[ExpectedSingleLineBlockEnd-43]
	_ = x[DuplicateAttribute-44]
	_ = x[DiagnosticKindCount-45]
}

const _DiagnosticKind_name = "InvalidUTF8InvalidCharacterUnterminatedBlockCommentUnterminatedQuotedTemplateUnterminatedTemplateSequenceInvalidEscapeNewlineInQuotedTemplateUnterminatedHeredocExpectedExpressionUnexpectedTokenExpectedClosingParenExpectedClosingBracketExpectedConditionalColonExpectedArgumentSeparatorExpectedAttributeNameExpectedFunctionNameExpectedOpeningParenInvalidLegacyIndexNestedAttributeSplatNestingLimitExceededInvalidNumberExpectedTupleSeparatorExpectedClosingBraceExpectedObjectValueSeparatorExpectedObjectItemSeparatorExpectedForVariableExpectedForInExpectedForColonExpectedForArrowUnexpectedForKeyUnexpectedForGroupingExpectedTemplateSequenceEndExpectedTemplateDirectiveUnknownTemplateDirectiveUnexpectedTemplateDirectiveExpectedTemplateEndIfExpectedTemplateEndForExpectedBodyItemExpectedAttributeOrBlockExpectedBodyItemSeparatorExpectedBlockOpeningBraceExpectedLiteralBlockLabelExpectedSingleLineAttributeExpectedSingleLineBlockEndDuplicateAttributeDiagnosticKindCount"

var _DiagnosticKind_index = [...]uint16{0, 11, 27, 51, 77, 105, 118, 141, 160, 178, 193, 213, 235, 259, 284, 305, 325, 345, 363, 383, 403, 416, 438, 458, 486, 513, 532, 545, 561, 577, 593, 614, 641, 666, 690, 717, 738, 760, 776, 800, 825, 850, 875, 902, 928, 946, 965}

func (i DiagnosticKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DiagnosticKind_index)-1 {
		return "DiagnosticKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DiagnosticKind_name[_DiagnosticKind_index[idx]:_DiagnosticKind_index[idx+1]]
}
