// Command genunicode regenerates the lexer's Unicode identifier tables.
// Run through go generate ./internal/lexer; normal builds need no network.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

const (
	version      = "17.0.0"
	sourceURL    = "https://www.unicode.org/Public/" + version + "/ucd/DerivedCoreProperties.txt"
	sourceSHA256 = "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08"
)

type interval struct{ lo, hi uint64 }

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	client := &http.Client{Timeout: 30 * time.Second}
	response, err := client.Get(sourceURL)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return fmt.Errorf("download: %s", response.Status)
	}
	data, err := io.ReadAll(io.LimitReader(response.Body, 4<<20))
	if err != nil {
		return err
	}
	if fmt.Sprintf("%x", sha256.Sum256(data)) != sourceSHA256 {
		return fmt.Errorf("Unicode source checksum mismatch")
	}

	tables := map[string][]interval{}
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		line, _, _ := strings.Cut(scanner.Text(), "#")
		fields := strings.Split(line, ";")
		if len(fields) != 2 {
			continue
		}
		property := strings.TrimSpace(fields[1])
		if property != "ID_Start" && property != "ID_Continue" {
			continue
		}
		loText, hiText, multiple := strings.Cut(strings.TrimSpace(fields[0]), "..")
		lo, err := strconv.ParseUint(loText, 16, 32)
		if err != nil {
			return err
		}
		hi := lo
		if multiple {
			hi, err = strconv.ParseUint(hiText, 16, 32)
			if err != nil {
				return err
			}
		}
		ranges := tables[property]
		if len(ranges) > 0 && lo == ranges[len(ranges)-1].hi+1 {
			ranges[len(ranges)-1].hi = hi
		} else {
			ranges = append(ranges, interval{lo, hi})
		}
		tables[property] = ranges
	}
	if err := scanner.Err(); err != nil {
		return err
	}
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by tools/genunicode; DO NOT EDIT.")
	fmt.Fprintf(&output, "// Unicode %s, %s\n// SHA-256: %s\n", version, sourceURL, sourceSHA256)
	fmt.Fprintln(&output, "// Derived Unicode data is covered by ../../LICENSE-UNICODE.\n\npackage lexer")
	for _, property := range []string{"ID_Start", "ID_Continue"} {
		name := "idStart"
		if property == "ID_Continue" {
			name = "idContinue"
		}
		fmt.Fprintf(&output, "\nvar %s = [...]runeRange{\n", name)
		for _, r := range tables[property] {
			fmt.Fprintf(&output, "{0x%X, 0x%X},\n", r.lo, r.hi)
		}
		fmt.Fprintln(&output, "}")
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile("unicode_tables.go", formatted, 0644)
}
