package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"net/http"
	"net/http/httptest"
	"reflect"
	"strings"
	"testing"
)

const fixture = `# DerivedCoreProperties-17.0.0.txt
# @missing: 0000..10FFFF; Other_ID_Start; <none>

# Derived Property: ID_Start
0041..005A    ; ID_Start # L&  [26] LATIN CAPITAL LETTER A..LATIN CAPITAL LETTER Z
005B..005C    ; ID_Start # merged with the previous range
0061..007A    ; ID_Start # L&  [26] LATIN SMALL LETTER A..LATIN SMALL LETTER Z
00AA          ; ID_Start # Lo       FEMININE ORDINAL INDICATOR
00AB          ; ID_Start # single code point merged with a single code point

# Total code points: 5

0030..0039    ; ID_Continue
003A          ; Lowercase # other properties are ignored
0041..005A    ; ID_Continue # non-adjacent ranges stay separate
0041..005A    ; Other_ID_Start; extra field # ignored: not two fields
`

func TestParsePropertiesMergesAdjacentRanges(t *testing.T) {
	tables, err := parseProperties([]byte(fixture))
	if err != nil {
		t.Fatal(err)
	}
	want := map[string][]interval{
		"ID_Start":    {{0x41, 0x5C}, {0x61, 0x7A}, {0xAA, 0xAB}},
		"ID_Continue": {{0x30, 0x39}, {0x41, 0x5A}},
	}
	if !reflect.DeepEqual(tables, want) {
		t.Fatalf("tables = %v, want %v", tables, want)
	}
}

func TestParsePropertiesRejectsMalformedInput(t *testing.T) {
	for name, source := range map[string]string{
		"invalid hex":          "00G1 ; ID_Start\n0041 ; ID_Continue\n",
		"invalid range end":    "0041..00G1 ; ID_Start\n0041 ; ID_Continue\n",
		"descending range":     "005A..0041 ; ID_Start\n0041 ; ID_Continue\n",
		"overlapping range":    "0041..005A ; ID_Start\n0050..0060 ; ID_Start\n0041 ; ID_Continue\n",
		"out of order range":   "0041..005A ; ID_Start\n0030..0039 ; ID_Start\n0041 ; ID_Continue\n",
		"missing property":     "0041 ; ID_Start\n",
		"empty input":          "",
		"comments only":        "# 0041 ; ID_Start\n# 0041 ; ID_Continue\n",
		"code point above max": "110000 ; ID_Start\n0041 ; ID_Continue\n",
	} {
		t.Run(name, func(t *testing.T) {
			if _, err := parseProperties([]byte(source)); err == nil {
				t.Fatal("expected an error")
			}
		})
	}
}

func TestParsePropertiesAcceptsMaximumCodePoint(t *testing.T) {
	tables, err := parseProperties([]byte("0041 ; ID_Start\n10FFFF ; ID_Continue\n"))
	if err != nil {
		t.Fatal(err)
	}
	if got := tables["ID_Continue"]; !reflect.DeepEqual(got, []interval{{0x10FFFF, 0x10FFFF}}) {
		t.Fatalf("ID_Continue = %v", got)
	}
}

func TestRenderEmitsFormattedTables(t *testing.T) {
	tables, err := parseProperties([]byte(fixture))
	if err != nil {
		t.Fatal(err)
	}
	output, err := render(tables)
	if err != nil {
		t.Fatal(err)
	}
	formatted, err := format.Source(output)
	if err != nil || !bytes.Equal(formatted, output) {
		t.Fatalf("output is not gofmt clean: %v", err)
	}
	for _, want := range []string{
		"// Code generated by tools/genunicode; DO NOT EDIT.",
		"package syntax",
		"// Unicode " + unicodeVersion + ",",
		"var idStart = [...]runeRange{\n\t{0x41, 0x5C},\n\t{0x61, 0x7A},\n\t{0xAA, 0xAB},\n}",
		"var idContinue = [...]runeRange{\n\t{0x30, 0x39},\n\t{0x41, 0x5A},\n}",
		sourceSHA256,
	} {
		if !strings.Contains(string(output), want) {
			t.Errorf("output lacks %q:\n%s", want, output)
		}
	}
	if strings.Index(string(output), "var idStart") > strings.Index(string(output), "var idContinue") {
		t.Error("idStart must precede idContinue")
	}
}

// serve returns a client and URL for a server that responds with body.
func serve(t *testing.T, status int, body []byte) (*http.Client, string) {
	t.Helper()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(status)
		w.Write(body)
	}))
	t.Cleanup(server.Close)
	return server.Client(), server.URL
}

func checksum(data []byte) string { return fmt.Sprintf("%x", sha256.Sum256(data)) }

func TestDownloadVerifiesResponses(t *testing.T) {
	// A response longer than maxSourceBytes is read only up to the limit, so
	// the checksum of the truncated prefix is what download compares; pinning
	// the checksum of the whole body is what makes truncation an error rather
	// than silently shorter tables.
	oversized := bytes.Repeat([]byte("a"), maxSourceBytes+16)
	for name, test := range map[string]struct {
		status int
		body   []byte
		pinned string
		want   string
	}{
		"checksum mismatch": {http.StatusOK, []byte("tampered"), checksum([]byte("official")), "does not match pinned"},
		"truncated body":    {http.StatusOK, oversized, checksum(oversized), "does not match pinned"},
		"not found":         {http.StatusNotFound, nil, checksum(nil), "404"},
	} {
		t.Run(name, func(t *testing.T) {
			client, url := serve(t, test.status, test.body)
			data, err := download(client, url, test.pinned)
			if data != nil {
				t.Fatalf("rejected download returned %d bytes", len(data))
			}
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("error = %v, want one containing %q", err, test.want)
			}
		})
	}
}

func TestDownloadAcceptsPinnedContent(t *testing.T) {
	body := []byte("0041 ; ID_Start\n")
	client, url := serve(t, http.StatusOK, body)
	data, err := download(client, url, checksum(body))
	if err != nil || !bytes.Equal(data, body) {
		t.Fatalf("download = %q, %v", data, err)
	}
}
