// Command genunicode regenerates the lexer's Unicode identifier tables.
// Run through go generate ./internal/syntax; normal builds need no network.
// The Unicode version and source checksum are intentionally pinned together:
// changing them changes the accepted HCL identifiers and requires review.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

const (
	version      = "17.0.0"
	sourceURL    = "https://www.unicode.org/Public/" + version + "/ucd/DerivedCoreProperties.txt"
	sourceSHA256 = "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08"
)

// properties lists the derived properties emitted, in output order, with the
// Go identifier each table receives.
var properties = []struct{ property, name string }{
	{"ID_Start", "idStart"},
	{"ID_Continue", "idContinue"},
}

type interval struct{ lo, hi uint64 }

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	data, err := download()
	if err != nil {
		return err
	}
	tables, err := parseProperties(data)
	if err != nil {
		return err
	}
	output, err := render(tables)
	if err != nil {
		return err
	}
	return os.WriteFile("unicode_tables.go", output, 0644)
}

func download() ([]byte, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	response, err := client.Get(sourceURL)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download: %s", response.Status)
	}
	data, err := io.ReadAll(io.LimitReader(response.Body, 4<<20))
	if err != nil {
		return nil, err
	}
	if fmt.Sprintf("%x", sha256.Sum256(data)) != sourceSHA256 {
		return nil, fmt.Errorf("unicode source checksum mismatch")
	}
	return data, nil
}

// parseProperties extracts the code point ranges of every property listed in
// properties from DerivedCoreProperties.txt. Adjacent ranges are merged; the
// file lists each property in ascending order, so merging only ever touches
// the previously emitted range.
func parseProperties(data []byte) (map[string][]interval, error) {
	wanted := make(map[string]bool, len(properties))
	for _, p := range properties {
		wanted[p.property] = true
	}
	tables := map[string][]interval{}
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		line, _, _ := strings.Cut(scanner.Text(), "#")
		fields := strings.Split(line, ";")
		if len(fields) != 2 {
			continue
		}
		property := strings.TrimSpace(fields[1])
		if !wanted[property] {
			continue
		}
		loText, hiText, multiple := strings.Cut(strings.TrimSpace(fields[0]), "..")
		lo, err := strconv.ParseUint(loText, 16, 32)
		if err != nil {
			return nil, err
		}
		hi := lo
		if multiple {
			hi, err = strconv.ParseUint(hiText, 16, 32)
			if err != nil {
				return nil, err
			}
		}
		if hi < lo || hi > 0x10FFFF {
			return nil, fmt.Errorf("invalid code point range %s", strings.TrimSpace(fields[0]))
		}
		ranges := tables[property]
		if len(ranges) > 0 && lo <= ranges[len(ranges)-1].hi+1 {
			if lo <= ranges[len(ranges)-1].hi {
				return nil, fmt.Errorf("%s: unordered or overlapping range %s", property, strings.TrimSpace(fields[0]))
			}
			ranges[len(ranges)-1].hi = hi
		} else {
			ranges = append(ranges, interval{lo, hi})
		}
		tables[property] = ranges
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	for _, p := range properties {
		if len(tables[p.property]) == 0 {
			return nil, fmt.Errorf("%s: no ranges found", p.property)
		}
	}
	return tables, nil
}

// render emits the gofmt-formatted Go source for unicode_tables.go.
func render(tables map[string][]interval) ([]byte, error) {
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by tools/genunicode; DO NOT EDIT.")
	fmt.Fprintln(&output, "// Pinned ID_Start/ID_Continue properties; see identifier.go for rationale and regeneration.")
	fmt.Fprintf(&output, "// Unicode %s, %s\n// SHA-256: %s\n", version, sourceURL, sourceSHA256)
	fmt.Fprintln(&output, "// Derived Unicode data is covered by ../../LICENSE-UNICODE.\n\npackage syntax")
	fmt.Fprintln(&output, "\n// UnicodeVersion pins identifiers independently of the Go toolchain's tables.")
	fmt.Fprintf(&output, "const UnicodeVersion = %q\n", version)
	for _, p := range properties {
		fmt.Fprintf(&output, "\nvar %s = [...]runeRange{\n", p.name)
		for _, r := range tables[p.property] {
			fmt.Fprintf(&output, "{0x%X, 0x%X},\n", r.lo, r.hi)
		}
		fmt.Fprintln(&output, "}")
	}
	return format.Source(output.Bytes())
}
